
---

#NGINX
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacklaravelnginx
  namespace: laravelapp
  labels:
    app: stacklaravelnginx
spec:
  selector:
    matchLabels:
      app: stacklaravelnginx
  replicas: 1
  template:
    metadata:
      labels:
        app: stacklaravelnginx
    spec:
      containers:
        - name: stacklaravelnginx
          image: paganuzzi/stacklaravel-nginx:v1.4.4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: stacklaravelnginx
  namespace: laravelapp
spec:
  selector:
    app: stacklaravelnginx
  type: ClusterIP
  ports:
    - name: stacklaravelnginx
      protocol: TCP
      port: 8000
      targetPort: 8000

#PHP FPM
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacklaravelphp
  namespace: laravelapp
  labels:
    app: stacklaravelphp
spec:
  selector:
    matchLabels:
      app: stacklaravelphp
  replicas: 5
  template:
    metadata:
      labels:
        app: stacklaravelphp
    spec:
      containers:
        - name: stacklaravelphp
          image: paganuzzi/php:1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: APP_KEY
              value: base64:3yJ5EsrnbK2c7BgWcHKqSuJ1efRc4CGrFVb6s/uac7E=
            - name: REDIS_HOST
              value: redislaravel-master
            - name: REDIS_PASSWORD 
              value: KhfqM8zVCW
            - name: MAIL_HOST 
              value: laravelpit
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  namespace: laravelapp
spec:
  selector:
    app: stacklaravelphp
  type: ClusterIP
  ports:
    - name: stacklaravelphp
      protocol: TCP
      port: 9000
      targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravelapp
  namespace: laravelapp
spec:
  rules:
    - host: laravel.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stacklaravelnginx
                port:
                  number: 8000





---
#Worker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stacklaravelworker
  namespace: laravelapp
  labels:
    app: stacklaravelworker
spec:
  selector:
    matchLabels:
      app: stacklaravelworker
  replicas: 4
  template:
    metadata:
      labels:
        app: stacklaravelworker
    spec:
      containers:
        - name: stacklaravelworker
          image: paganuzzi/php:1
          command:
            - php
          args:
            - artisan
            - queue:work
            - "--timeout=0"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: APP_KEY
              value: base64:3yJ5EsrnbK2c7BgWcHKqSuJ1efRc4CGrFVb6s/uac7E=
            - name: REDIS_HOST
              value: redislaravel-master
            - name: REDIS_PASSWORD 
              value: KhfqM8zVCW
            - name: MAIL_HOST 
              value: laravelpit
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi



---
#MailPit

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravelpit
  namespace: laravelapp
  labels:
    app: laravelpit
spec:
  selector:
    matchLabels:
      app: laravelpit
  replicas: 1
  template:
    metadata:
      labels:
        app: laravelpit
    spec:
      containers:
        - name: laravelpit
          image: axllent/mailpit
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi




---
#MailPitSVC
apiVersion: v1
kind: Service
metadata:
  name: laravelpit
  namespace: laravelapp
spec:
  selector:
    app: laravelpit
  type: ClusterIP
  ports:
    - name: web
      protocol: TCP
      port: 8025
      targetPort: 8025
    - name: laravelpit
      protocol: TCP
      port: 1025
      targetPort: 1025
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: laravelpit
  namespace: laravelapp
spec:
  rules:
    - host: laravelpit.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: laravelpit
                port:
                  number: 8025
